# Generated by Django 4.0.2 on 2022-02-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_pref', models.CharField(max_length=7)),
                ('q1', models.CharField(max_length=3)),
                ('q2', models.CharField(max_length=4)),
                ('q3', models.CharField(max_length=12)),
            ],
        ),
    ]
