# Generated by Django 4.0.2 on 2022-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_survey_liquor_pref_alter_survey_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='instructions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='liquor_pref',
            field=models.CharField(choices=[('V', 'Vodka'), ('G', 'Gin'), ('R', 'Rum'), ('T', 'Tequila')], default='V', max_length=1, verbose_name='What is your preferred liquor?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q1',
            field=models.CharField(choices=[('W', 'Work'), ('P', 'Play')], default='W', max_length=1, verbose_name='Was Today work or play?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q2',
            field=models.CharField(choices=[('A', 'Adventurous'), ('C', 'Classic')], default='A', max_length=1, verbose_name='Are you feeling adventurous or classic?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q3',
            field=models.CharField(choices=[('P', 'Pick-Me-Up'), ('R', 'Relaxation')], default='P', max_length=1, verbose_name='Do you need a pick-me-up or to relax?'),
        ),
    ]
